### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Rkomi98** [Rkomi98/DECODE#1]
Next steps
- [ ] Create a public website
- [ ] Add the dashboard
- [ ] play with geospatial data
- [ ] test the website
